# Camera and Scale Configuration
scale:
  # Known height of scale in cm
  total_height: 45.5
  # Width of scale in cm (for reference)
  width: 5.0
  # Scale position in image (if fixed)
  expected_position:
    x_min: 81
    x_max: 194
    y_min: 1
    y_max: 550
  
  # RGB/HSV color-based scale detection
  color_detection:
    enabled: true
    adaptive_thresholding: true
    debug_color_masks: true
    
    # Scale color definitions (HSV ranges)
    scale_colors:
      yellow:
        enabled: false
        hsv_lower: [20, 100, 100]
        hsv_upper: [30, 255, 255]
        description: "Yellow scale background"
      
      white:
        enabled: false
        hsv_lower: [1, 0, 0]
        hsv_upper: [164, 108, 255]
        description: "White scale background"
      
      blue:
        enabled: true
        hsv_lower: [94, 12, 155]
        hsv_upper: [114, 120, 255]
        description: "Blue scale background"

      black:
        enabled: true
        hsv_lower: [43, 0, 0]
        hsv_upper: [179, 61, 90]
        description: "Black scale markings"
      
      red:
        enabled: false
        hsv_lower: [0, 100, 100]
        hsv_upper: [10, 255, 255]
        description: "Red scale background"
      
      red_alt:
        enabled: false
        hsv_lower: [170, 100, 100]
        hsv_upper: [180, 255, 255]
        description: "Red scale background (alt range)"
      
      white_markings:
        enabled: false
        hsv_lower: [0, 0, 220]
        hsv_upper: [180, 20, 255]
        description: "White scale markings on colored backgrounds"
    
    # Morphological operations for mask cleanup
    morphology:
      kernel_size: 3
      close_iterations: 1
      open_iterations: 1

calibration:
  # Pixels per centimeter (will be calculated during calibration)
  pixels_per_cm: null
  # Reference water level for calibration (cm)
  reference_water_level: 23.1
  # Use enhanced calibration data with waterline gradient analysis
  use_enhanced_data: true
  enhanced_data_path: 'data/calibration/calibration.yaml'

detection:
  # Water line detection parameters
  edge_threshold_low: 50
  edge_threshold_high: 150
  blur_kernel_size: 7
  min_contour_area: 500
  
  # Water detection method: 'edge', 'color', 'gradient', 'integrated' (runs all methods)
  method: 'integrated'
  
  # Force a specific method while still running all methods for comparison
  # Options: 'enhanced_gradient', 'edge', 'color', 'gradient', null (use consensus)
  # When set, this method will be used as final result, but all methods still run and log results
  forced_method: 'enhanced_gradient'
  
  # Color-based detection (HSV ranges for water)
  water_hsv_lower: [31, 0, 0]
  water_hsv_upper: [61, 92, 112]
  
  # NEW: Pattern-aware detection system
  pattern_aware:
    engine: 'integrated_pattern'      # Pattern detection engine
    fallback_to_standard: true        # Fall back to standard methods if pattern fails
    
    # E-pattern sequential detection settings
    e_pattern_detection:
      enabled: true                   # Enable E-pattern sequential detector
      single_e_cm: 5.0                # E_pattern_black/white correspond to 5 cm
      match_threshold: 0.7           # Template matching threshold for E-patterns
      max_consecutive_failures: 6     # Stop after N failures (likely reached water)
      support_flipped: false          # Support 180-degree flipped patterns
    
    # Pattern recognition settings
    template_matching:
      enabled: true
      threshold: 0.75                 # Template match confidence
      max_templates: 10               # Maximum templates to store
      template_source: 'manager'      # Options: 'local', 'manager', 'both'
      use_default_templates: true     # Create default stadia rod templates
      
      # Advanced template matching settings
      preprocessing:
        mean_shift_filtering: true      # Apply mean shift filtering for noise reduction
        adaptive_thresholding: true     # Use adaptive thresholding for better contrast
        morphological_cleaning: true    # Apply morphological operations
      
      nms:
        enabled: true                   # Enable Non-Maximum Suppression
        threshold: 0.4                  # NMS overlap threshold
        confidence_threshold: 0.5       # Minimum confidence for NMS
      
      # Template-specific thresholds (override global threshold)
      template_thresholds:
        e_major: 0.6                    # E-pattern major graduations
        line_minor: 0.7                 # Simple line minor graduations
        line_thick: 0.65                # Thick line intermediate graduations
        number_marking: 0.5             # Number markings on rod
        l_major: 0.6                    # L-shaped major graduations
    
    morphological:
      enabled: true
      horizontal_kernel_size: [40, 1] # Horizontal feature detection
      vertical_kernel_size: [1, 40]   # Vertical feature suppression
    
    frequency_analysis:
      enabled: true
      periodicity_threshold: 0.3      # Max periodicity for water interface
    
    line_detection:
      enabled: true
      min_line_length_ratio: 0.6      # Minimum line length (% of scale width)
      max_angle_deviation: 10         # Max angle from horizontal (degrees)
    
    contour_analysis:
      enabled: true
      min_aspect_ratio: 10            # Minimum width/height ratio
      min_width_ratio: 0.5            # Minimum width (% of scale width)
    
    # Hybrid waterline verification system
    waterline_verification:
      enabled: true                   # Enable hybrid waterline verification
      enable_fallback_regions: false   # Enable extended regions below primary region (set to false for primary region only)
      min_pattern_confidence: 0.7     # Minimum confidence for waterline detection
      gradient_kernel_size: 3         # Sobel kernel size for gradient analysis
      gradient_threshold: 25          # Threshold for significant gradient changes
      negative_gradient_threshold: 25 # Minimum absolute value for negative gradient differentials (waterline detection)
      negative_sobel_threshold: 40    # Threshold for negative raw Sobel gradients (blue signature detection)
      
      # Pattern analysis thresholds (used for both consecutive pattern detection and anomaly detection)
      pattern_analysis:
        # Consecutive good pattern detection thresholds
        scale_consistency_threshold: 0.15    # Scale factor consistency for consecutive good patterns (±15%)
        size_consistency_threshold: 0.15     # Size consistency for consecutive good patterns (±25%) 
        spacing_consistency_threshold: 0.10  # Spacing consistency for consecutive good patterns (±50%)
        min_consecutive_patterns: 0          # Minimum consecutive good patterns required
        
        # Anomaly detection thresholds (applied after establishing baseline)
        scale_anomaly_threshold: 0.20        # Scale factor change to flag suspicious regions (±15%)
        size_anomaly_threshold: 0.20         # Size change to flag suspicious regions (±20%)
        aspect_ratio_anomaly_threshold: 0.20 # Aspect ratio change to flag suspicious regions (±20%)
        max_gap_ratio: 0.5                   # Max gap between patterns (2x expected spacing)
        
        # Baseline buffer configuration - percentage of average pattern height for symmetric region around baseline
        # This creates equal coverage above and below the last detected pattern
        baseline_buffer_percentage: 0.6   # Buffer as % of avg pattern height (symmetric coverage)
      
      # Candidate density-based clustering for improved selection
      candidate_clustering:
        enabled: true                     # Enable density-based candidate selection
        cluster_height_cm: 5.0            # Height of clustering region in cm (default 5cm)
        min_candidates_in_cluster: 2      # Minimum candidates required to form a cluster
        use_median_selection: false       # Use median instead of highest confidence within cluster
        max_cluster_centers: 10           # Maximum number of top candidates to evaluate as cluster centers

processing:
  # Image processing settings
  resize_width: null  # 800 # Use "null" to disable resizing & use original image dimensions
  save_processed_images: true
  image_format: 'jpg'

# NEW: Pattern-aware processing mode
pattern_processing:
  mode: 'pattern_aware'               # Options: 'standard', 'pattern_aware', 'hybrid'
  debug_patterns: true                # Save pattern analysis debug images
  save_templates: true                # Save extracted templates for reuse
  template_directory: 'data/pattern_templates/scale_markings'
  
output:
  # Output settings
  csv_export: true
  json_export: true
  database: true

debug:
  # Visual debugging options
  enabled: true
  save_debug_images: true
  debug_output_dir: 'data/debug'
  annotation_color: [0, 255, 0]  # Green BGR
  annotation_thickness: 2
  font_scale: 0.7
  steps_to_save:
      # Standard detection debugging steps (used by both standard and pattern-aware detectors)
      - 'original'
      - 'preprocessed'
      - 'color_mask_blue'           # NEW - see blue color detection
      - 'color_mask_black'          # NEW - see black color detection  
      - 'color_mask_combined'       # NEW - see combined color mask
      - 'masked_grayscale'          # NEW - see color-filtered grayscale
      - 'edges'
      - 'edges_color_enhanced'      # NEW - color-enhanced edge detection
      - 'edges_masked_gray'         # NEW - canny edges on color-masked grayscale
      - 'edges_multi_channel'       # NEW - combined edges from RGB channels
      - 'edges_hue_transitions'     # NEW - hue channel color transition edges
      - 'edges_individual_colors'   # NEW - edges from individual color masks
      - 'edges_final_combined'      # NEW - final combined color-enhanced edges
      - 'scale_contours_analysis'   # NEW - see contour scoring
      - 'scale_bounds_enhanced'     # NEW - see detected scale bounds
      - 'scale_region_extracted'    # NEW - see extracted scale region
      - 'contours'
      - 'waterline_within_scale'    # NEW - see waterline detection
      - 'scale_detection'
      - 'water_detection'
      - 'water_color_mask'          # NEW - water color mask visualization
      - 'hsv_conversion'            # NEW - HSV color space conversion
      - 'gradient_analysis'           # NEW - vertical gradient analysis (Sobel)
      - 'integrated_detection_methods'  # NEW - multi-method detection visualization
      - 'final_result'
      
      # Pattern-aware specific debugging steps (filtered out for standard detector)
      # These are only used when pattern-aware detection is enabled
      - 'pattern_original'          # Original image for pattern processing
      - 'pattern_scale_region'      # Extracted scale region for pattern analysis
      - 'pattern_preprocessing'     # Scale region preprocessed for pattern detection
      - 'pattern_e_pattern_result'  # E-pattern sequential detection results
      - 'pattern_template_matching_result'  # Template matching results
      - 'pattern_morphological_result'      # Morphological analysis results
      - 'pattern_frequency_result'          # Frequency analysis results
      - 'pattern_lsd_result'                # Line segment detection results
      - 'pattern_contour_result'            # Contour analysis results
      - 'pattern_methods_summary'           # Summary of all pattern method results
      - 'pattern_water_detection'           # Final pattern-based water line detection
      - 'waterline_verification_analysis'   # Hybrid waterline verification process
      - 'waterline_gradient_analysis'       # Gradient analysis debug visualization
      - 'waterline_gradient_analysis_clean' # Gradient image without annotations
      - 'waterline_candidate_regions'      # Suspicious regions identified by pattern analysis