# Camera and Scale Configuration
scale:
  # Known height of scale in cm
  total_height: 455.0
  # Width of scale in cm (for reference)
  width: 5.0
  # Scale position in image (if fixed)
  expected_position:
    x_min: 81
    x_max: 194
    y_min: 1
    y_max: 550
  
  # RGB/HSV color-based scale detection
  color_detection:
    enabled: true
    adaptive_thresholding: true
    debug_color_masks: true
    
    # Scale color definitions (HSV ranges)
    scale_colors:
      yellow:
        enabled: false
        hsv_lower: [20, 100, 100]
        hsv_upper: [30, 255, 255]
        description: "Yellow scale background"
      
      white:
        enabled: false
        hsv_lower: [1, 0, 0]
        hsv_upper: [164, 108, 255]
        description: "White scale background"
      
      blue:
        enabled: true
        hsv_lower: [94, 12, 155]
        hsv_upper: [114, 120, 255]
        description: "Blue scale background"

      black:
        enabled: true
        hsv_lower: [0, 0, 0]
        hsv_upper: [166, 72, 88]
        description: "Black scale markings"
      
      red:
        enabled: false
        hsv_lower: [0, 100, 100]
        hsv_upper: [10, 255, 255]
        description: "Red scale background"
      
      red_alt:
        enabled: false
        hsv_lower: [170, 100, 100]
        hsv_upper: [180, 255, 255]
        description: "Red scale background (alt range)"
      
      white_markings:
        enabled: false
        hsv_lower: [0, 0, 220]
        hsv_upper: [180, 20, 255]
        description: "White scale markings on colored backgrounds"
    
    # Morphological operations for mask cleanup
    morphology:
      kernel_size: 3
      close_iterations: 1
      open_iterations: 1

calibration:
  # Pixels per centimeter (will be calculated during calibration)
  pixels_per_cm: null
  # Reference water level for calibration (cm)
  reference_water_level: 235.0
  # Use enhanced calibration data with waterline gradient analysis
  use_enhanced_data: true
  enhanced_data_path: 'data/calibration/calibration.yaml'

detection:
  # Water line detection parameters
  edge_threshold_low: 50
  edge_threshold_high: 150
  blur_kernel_size: 7
  min_contour_area: 500
  
  # Water detection method: 'edge', 'color', 'gradient', 'integrated' (runs all methods)
  method: 'integrated'
  
  # Force a specific method while still running all methods for comparison
  # Options: 'enhanced_gradient', 'edge', 'color', 'gradient', null (use consensus)
  # When set, this method will be used as final result, but all methods still run and log results
  forced_method: 'enhanced_gradient'
  
  # Color-based detection (HSV ranges for water)
  water_hsv_lower: [78, 9, 98]
  water_hsv_upper: [108, 129, 218]
  
  # NEW: Pattern-aware detection system
  pattern_aware:
    enabled: false                    # Enable pattern-aware detection
    engine: 'integrated_pattern'      # Pattern detection engine
    fallback_to_standard: true        # Fall back to standard methods if pattern fails
    
    # Pattern recognition settings
    template_matching:
      enabled: true
      threshold: 0.7                  # Template match confidence
      max_templates: 10               # Maximum templates to store
    
    morphological:
      enabled: true
      horizontal_kernel_size: [40, 1] # Horizontal feature detection
      vertical_kernel_size: [1, 40]   # Vertical feature suppression
    
    frequency_analysis:
      enabled: true
      periodicity_threshold: 0.3      # Max periodicity for water interface
    
    line_detection:
      enabled: true
      min_line_length_ratio: 0.6      # Minimum line length (% of scale width)
      max_angle_deviation: 10         # Max angle from horizontal (degrees)
    
    contour_analysis:
      enabled: true
      min_aspect_ratio: 10            # Minimum width/height ratio
      min_width_ratio: 0.5            # Minimum width (% of scale width)

processing:
  # Image processing settings
  resize_width: null  # 800 # Use "null" to disable resizing & use original image dimensions
  save_processed_images: true
  image_format: 'jpg'

# NEW: Pattern-aware processing mode
pattern_processing:
  mode: 'standard'                    # Options: 'standard', 'pattern_aware', 'hybrid'
  debug_patterns: false               # Save pattern analysis debug images
  save_templates: true                # Save extracted templates for reuse
  template_directory: 'data/pattern_templates/scale_markings'
  
output:
  # Output settings
  csv_export: true
  json_export: true
  database: true

debug:
  # Visual debugging options
  enabled: true
  save_debug_images: true
  debug_output_dir: 'data/debug'
  annotation_color: [0, 255, 0]  # Green BGR
  annotation_thickness: 2
  font_scale: 0.7
  steps_to_save:
      - 'original'
      - 'preprocessed'
      - 'color_mask_blue'           # NEW - see blue color detection
      - 'color_mask_black'          # NEW - see black color detection  
      - 'color_mask_combined'       # NEW - see combined color mask
      - 'masked_grayscale'          # NEW - see color-filtered grayscale
      - 'edges'
      - 'scale_contours_analysis'   # NEW - see contour scoring
      - 'scale_bounds_enhanced'     # NEW - see detected scale bounds
      - 'scale_region_extracted'    # NEW - see extracted scale region
      - 'contours'
      - 'waterline_within_scale'    # NEW - see waterline detection
      - 'scale_detection'
      - 'water_detection'
      - 'final_result'