# Camera and Scale Configuration
scale:
  # Known height of scale in cm
  total_height: 450.0
  # Width of scale in cm (for reference)
  width: 8.0
  # Scale position in image (if fixed)
  expected_position:
    x_min: 81
    x_max: 181
    y_min: 1
    y_max: 603
  
  # RGB/HSV color-based scale detection
  color_detection:
    enabled: true
    adaptive_thresholding: true
    debug_color_masks: true
    
    # Scale color definitions (HSV ranges)
    scale_colors:
      yellow:
        enabled: true
        hsv_lower: [20, 100, 100]
        hsv_upper: [30, 255, 255]
        description: "Yellow scale background"
      
      white:
        enabled: true
        hsv_lower: [1, 0, 0]
        hsv_upper: [164, 108, 255]
        description: "White scale background"
      
      blue:
        enabled: true
        hsv_lower: [94, 12, 155]
        hsv_upper: [114, 112, 255]
        description: "Blue scale background"

      black:
        enabled: true
        hsv_lower: [97, 0, 0]
        hsv_upper: [129, 92, 87]
        description: "Black scale markings"
      
      red:
        enabled: true
        hsv_lower: [0, 100, 100]
        hsv_upper: [10, 255, 255]
        description: "Red scale background"
      
      red_alt:
        enabled: true
        hsv_lower: [170, 100, 100]
        hsv_upper: [180, 255, 255]
        description: "Red scale background (alt range)"
      
      white_markings:
        enabled: true
        hsv_lower: [0, 0, 220]
        hsv_upper: [180, 20, 255]
        description: "White scale markings on colored backgrounds"
    
    # Morphological operations for mask cleanup
    morphology:
      kernel_size: 3
      close_iterations: 1
      open_iterations: 1

calibration:
  # Pixels per centimeter (will be calculated during calibration)
  pixels_per_cm: null
  # Reference water level for calibration (cm)
  reference_water_level: 50.0

detection:
  # Water line detection parameters
  edge_threshold_low: 50
  edge_threshold_high: 150
  blur_kernel_size: 7
  min_contour_area: 500
  
  # Water detection method: 'edge', 'color', 'gradient'
  method: 'edge'
  
  # Color-based detection (HSV ranges for water)
  water_hsv_lower: [100, 50, 50]
  water_hsv_upper: [130, 255, 255]

processing:
  # Image processing settings
  resize_width: 800  # Resize images for faster processing
  save_processed_images: true
  image_format: 'jpg'
  
output:
  # Output settings
  csv_export: true
  json_export: true
  database: true

debug:
  # Visual debugging options
  enabled: false
  save_debug_images: true
  debug_output_dir: 'data/debug'
  annotation_color: [0, 255, 0]  # Green BGR
  annotation_thickness: 2
  font_scale: 0.7
  steps_to_save:
    - 'original'
    - 'preprocessed' 
    - 'edges'
    - 'contours'
    - 'scale_detection'
    - 'water_detection'
    - 'final_result'